// File generated by FlutterFire CLI.
// The FlutterFire CLI is an extension of the Firebase CLI. Although it is a
// separate project, it uses the same authentication and project selection.
// More information: https://github.com/invertase/flutterfire_cli

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macOS;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'your-api-key',
    appId: '1:1021282595697:android:1ca5705a42a81cb155fcd0',
    messagingSenderId: '1021282595697',
    projectId: 'flutterstudy30',
    storageBucket: 'your-storage-bucket',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your-api-key',
    appId: '1:1021282595697:ios:1ca5705a42a81cb155fcd0',
    messagingSenderId: '1021282595697',
    projectId: 'flutterstudy30',
    storageBucket: 'your-storage-bucket',
  );

  static const FirebaseOptions macOS = FirebaseOptions(
    apiKey: 'your-api-key',
    appId: '1:1021282595697:macos:1ca5705a42a81cb155fcd0',
    messagingSenderId: '1021282595697',
    projectId: 'flutterstudy30',
    storageBucket: 'your-storage-bucket',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your-api-key',
    appId: '1:1021282595697:web:1ca5705a42a81cb155fcd0',
    messagingSenderId: '1021282595697',
    projectId: 'flutterstudy30',
    authDomain: 'flutterstudy30.firebaseapp.com',
    storageBucket: 'flutterstudy30.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your-api-key',
    appId: 'your-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    authDomain: 'your-project-id.firebaseapp.com',
    storageBucket: 'your-storage-bucket',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'your-api-key',
    appId: 'your-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    authDomain: 'your-project-id.firebaseapp.com',
    storageBucket: 'your-storage-bucket',
  );
}
