// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz9UeIdNZTE42wfhobeLkQUcY6nO9CLxw',
    appId: '1:1057773922337:web:025e09877a4ccc07201b60',
    messagingSenderId: '1057773922337',
    projectId: 'flutterstudy30-b9cbe',
    authDomain: 'flutterstudy30-b9cbe.firebaseapp.com',
    storageBucket: 'flutterstudy30-b9cbe.firebasestorage.app',
    measurementId: 'G-F0951G5JM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeEeJtRxB-5xb4aLyTpsLjdI5y3tV4diE',
    appId: '1:1057773922337:android:68bde3ebd0109244201b60',
    messagingSenderId: '1057773922337',
    projectId: 'flutterstudy30-b9cbe',
    storageBucket: 'flutterstudy30-b9cbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL0KEneDO6f3dVQIMKW9F2HpCeDD2bI9I',
    appId: '1:1057773922337:ios:c235dd63a1bc1842201b60',
    messagingSenderId: '1057773922337',
    projectId: 'flutterstudy30-b9cbe',
    storageBucket: 'flutterstudy30-b9cbe.firebasestorage.app',
    iosBundleId: 'com.zilzilastudy.flutterStudy30',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL0KEneDO6f3dVQIMKW9F2HpCeDD2bI9I',
    appId: '1:1057773922337:ios:0bcd59a1104524a9201b60',
    messagingSenderId: '1057773922337',
    projectId: 'flutterstudy30-b9cbe',
    storageBucket: 'flutterstudy30-b9cbe.firebasestorage.app',
    iosBundleId: 'com.example.flutterStudy30',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz9UeIdNZTE42wfhobeLkQUcY6nO9CLxw',
    appId: '1:1057773922337:web:ac5bb48279735bc8201b60',
    messagingSenderId: '1057773922337',
    projectId: 'flutterstudy30-b9cbe',
    authDomain: 'flutterstudy30-b9cbe.firebaseapp.com',
    storageBucket: 'flutterstudy30-b9cbe.firebasestorage.app',
    measurementId: 'G-WWS2YSTGFW',
  );
}
